name: publish-docs

on:
  push:
    branches:
      - main


jobs:

  deploy:
  
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install required packages
        run: sudo $GITHUB_WORKSPACE/.ci_scripts/publish-docs/install_packages.sh

      - name: Generate Doxygen documentation
        run: doxygen $GITHUB_WORKSPACE/Doxyfile

      - name: Create .nojekyll
        run: touch docs/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
